### ISSUE TITLE
UI crashes on Windows 11

### ISSUE THREAD

**Issue by EladBarkay** [rocksdanister/lively-webpage#154]
After installing it from the official microsoft store and opening it, the UI crashes and cannot be opened even after restarting the whole system.

But, the program does work in the background - meaning that i can change wallpapers throw the task bar icons, and i can even open the wallpaper customizations menu and customize wallpapers

That's how the app UI looks when trying to open it:

![image](https://github.com/rocksdanister/lively-webpage/assets/72928578/b8b96c56-453a-446a-a30c-be3b0cdceeb2)

**Comment by rocksdanister** [comment]
This seems to be https://github.com/rocksdanister/lively/issues/2187#issuecomment-2049024898

Can you try changing region.
